### ISSUE TITLE
Agent: consider using ActivityStreams subclasses

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/forum.valueflo.ws#120]
Looked for an existing issue to continue, but couldn't find the right one, so starting a new one.... and using ValueFlows repo for simplicity.

We are doing some work to use VF in an ActivityPub (uses ActivityStreams vocab) implementation.  We decided at one point to use just foaf:Person and org:Organization as subclasses of foaf:Agent.  There was a technical issue with foaf:Group which I don't remember the details of, brought by @elf-pavlik .  AS has Person, Group, Organization - although they are subclasses of as:Object.  Seems like a good thing to sync up with, if there aren't any problems with it, since it was made a W3C recommendation earlier this year, and ActivityPub is getting some traction.  In practice, we'll want to use the as:Group, as:Organization, as:Person as we do this particular integration.

Would switching to the AS classes for VF cause any technical or conceptual problems?  For example, we need the foaf:Agent superclass still, and these would need to be subclasses of that in our model.  Another example, AP considers these "[actors](https://www.w3.org/TR/activitypub/#actors)", somewhat more around distributed communication, like they have an inbox and outbox.  ActivityStreams has [this definition](https://www.w3.org/TR/activitystreams-core/#actors).  Repeating here:
```
Actor objects are specializations of the base Object type that represent entities capable of carrying out an Activity. The Activity Vocabulary provides the normative definition of five specific types of Actors: Application | Group | Organization | Person | Service.

This specification intentionally defines Actors in only the most generalized way, stopping short of defining semantically specific properties for each. All Actor objects are specializations of Object and inherit all of the core properties common to all Objects. External vocabularies can be used to express additional detail not covered by the Activity Vocabulary. VCard [ vcard-rdf] SHOULD be used to provide additional metadata for Person, Group, and Organization instances.
```
An example snippet:
```
{
  "actor": {
    "type": ["Person", "vcard:Individual"],
    "id": "http://sally.example.org",
    "name": "Sally Smith",
    "vcard:given-name": "Sally",
    "vcard:family-name": "Smith"
  },
```
We think of our subclasses in a more agent-y way, in the real world.  But they mix that in too.

Or is there a better way to think about integrating?  Some definition of owl:equivalentClass or similar?  And if so, how do we get Group in there?

**Comment by elf-pavlik** [comment]
We always have an option `"@type": [ "org:Organization", "as:Organization"]` and `"@type: ["foaf:Person", "as:Person"]`. To simplify queries we might actually require to [Materialize Inferences](http://patterns.dataincubator.org/book/materialize-inferences.html) which would include always asserting the parent type
* `"@type": ["foaf:Agent", "foaf:Person"]`
* `"@type": ["foaf:Agent", "org:Organization"]`

This way to query for all the agents one can use single query, instead of three queries: 1 - agent, 2 - person 3 - organization
As soon as we created extensive dataset based on use cases we work with, we will have better grounds to see all those trade offs.
For this issue I just want to point out, that if we end up with requirement to materialize inferences, throwing additional third of fourth type just to align with ActivityPub of whatever else whouldn't make big impact on implementations.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/120.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
