### ISSUE TITLE
ssb/matrix replication  protocol

### ISSUE THREAD

**Issue by orangeman** [valueflows/forum.valueflo.ws#129]
What do you think about using valueflows vocab via matrix protocol (kappa architecture style)?

Secure Scuttlebutt has been mentioned a lot here and also the matrix protocol. Afaics they work similar using a (cypherlink/hashpointer) git-like (merkle dag) datastructure in order to replicate partition tolerant data eventually consistent. (Nodes basically do git fetch && git merge && git push between each other). Some pub/sub (activity stream) syndication works fine as long as there is only one publishing node per feed. As soon as there are distributed apps publishing simultaneously some sort of data conflict reconciliation becomes necessary (branch/merge)

In addition to p2p data replication matrix also has a client-server protocol optionally off-lifting weight. Light clients can selectively page through (filtered) chatrooms and do not need to synchronize the whole feed. Matrix also elegantly bridges third-party identities (delegated oauth) and adds sophisticated (multi-party) e2e encryption and roles (power-levels) to implement (trustless) access control (acl) and confidentiality etc...

Eg in a federated food network farms would be simple private matrix rooms where participants coordinate their work: (crop) planing (todo) commitments from (howto) recipes and logging observed (done) events. Another public matrix room could publish intents/wants like product offers etc... Various (small scope) apps would kind of "_chat_" with each other and matrix makes sure every app eventually arrives on the same page (ie consistent data state). And "_the accounting (for accountability) just happens_" ;)

Curious if this is how you envision the valueflows vocabulary being used in a protocol (language)

related https://github.com/valueflows/forum.valueflo.ws/issues/70

**Comment by bhaugen** [comment]
@orangeman I am definitely planning to implement something like kappa-style in valueflows projects using ActivityPub and Holochain, and I think that Luandro will do something similar in his Scuttlebutt project (because that's how SSB works). 

Here are a couple of related threads:
* https://github.com/valueflows/vf-apps-agents/issues/1#issuecomment-459820495
* https://www.loomio.org/d/WVfZM3UA/requirements-for-a-protocol-for-agent-centric-p2p-economic-networks

I am not familiar with Matrix, so can't comment on that paragraph, but it looks like that whole scenario would work in any of those architectures.

If you have experience with such architectures, please take a look at this issue: https://github.com/valueflows/vf-apps-agents/issues/1

And https://www.loomio.org/d/WVfZM3UA/requirements-for-a-protocol-for-agent-centric-p2p-economic-networks

Maybe we should add Matrix to the mix...?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/129.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
