### ISSUE TITLE
Transactions and CfA

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#133]
CfA = Conversations for Action. See #131 

These are some considerations about implementing CfA's.

By "transactions", in this issue, I mean in the distributed data sense, not in the economic sense. In the distributed data sense, a transaction is an agreement on a state change between 2 or more agents communicating from different systems on a distributed network.

Agreeing on state changes on a distributed network is tricky, as [The 8 fallacies of distributed systems](https://www.simpleorientedarchitecture.com/8-fallacies-of-distributed-systems/) will explain. 

Here I will talk about the first two fallacies:
1. The network is reliable
2. Latency is zero

Not only will the network and the devices fail, so will the people, sometimes deviously.

And you can't really tell how long it will take to get a response from another system.

This diagram has two agents, 9 different states, and several ways to transition between them.
![cfa diagram](https://user-images.githubusercontent.com/117439/56866852-dffd0e80-69a3-11e9-8b06-a560786aa545.png)

Each of those state transitions requires agreement between each of the agents: sometimes just an acknowledgment, sometimes acceptance or rejection or some other meaningful response.

Thus, each of those state transitions requires a distributed transaction.

@fosterlynn and I put [a lot of notes about two-agent distributed transactions in this google doc](https://docs.google.com/document/d/1g8NUOziTtFJIzVc2uJTcwQycC_cuTKTbErkCXW7JegM/edit?usp=sharing).

It gets pretty complicated. But the guts of what we need for a 2-agent conversation for action are probably in the section entitled "The BTP doc also allows an event simpler variation: One-phase confirmation". 

That's the simplest distributed transaction protocol. But it has a hole, which our notes explain in terms of a simple mutual credit transfer:
> Situation: transferring mutual credits from one agent/account to another, where the accounts are not in the same mutual credit network. The providing agent initiates the transfer. If the transfer is successful (accepted by the receiving agent), both accounts will be updated: the providing account will be decremented, and the receiving account will be incremented. 

> But what happens if the providing agent does not get any response - neither acceptance nor rejection? What should the providing agent (or the transferring software) do?

One possibility is to set a timeout for the response, and for the waiting agent to fail that particular transaction, and then try to communicate with the responding agent and restart the CfA from the previous state. If still no response, the whole conversation may fail.

> **Complication:** mutual credit networks according to MatSlats have an invariant rule that the sum of all account balances must be zero. So that means the mutual credit network or networks are also a party, or parties, to this mutual credit transfer transaction. Which also means that neither of the agent account balances can be changed independently: they can only be changed when the mutual credit network or networks says it’s ok. So that makes it a 3 or 4 party consensus situation. Which means the coordinator, usually the provider in this case, needs to check also the decision or decisions of the network or networks. Here’s an example of a 3-party transaction: https://drive.google.com/open?id=1NkAY4QhI1ra2vjFvY1GzPPJXvYWJDgxg

Holochain validation might take care of that complication, or not. We still may need a designated coordinator, which is usually the originator of the transaction.

**Comment by bhaugen** [comment]
One question about all of those complications is, in what circumstances do you need all that formality?

Most mutual credit systems get by fine with an offer or request, then some emails and phone calls or face-to-face visits, and then one mutual credit transfer.

But if you are doing regular business, as with [Susan in slide 6 of Pavel Hruby's REA deck](https://www.slideshare.net/Demetrius_Gallitzin/PavelHruby), she wants a better record of who paid how much for what, when, and why. And if you have an organization larger than one person, you might need even more controls.

And if you don't trust your trading partners, you might want some non-repudiable evidence of what they agreed to. (Even if you do trust them, human memories are not perfect...)

**Comment by bhaugen** [comment]
One more angle: Jamie Clark, a contract lawyer, wrote this version of a conversation for action:
http://www.ebxml.org/specs/bpPATT_print.pdf

He makes the point that a counter-offer is also a rejection of the previous offer, and fails the transaction where that previous offer was trying to be accepted. The previous offer is no longer on the table. The counter-offer is now on the table.

Lynn makes the point that rejection of any offer fails the whole CfA. Only acceptance and counter-offer keep the conversation alive, and acceptance finishes the negotiation phase.

Is everybody getting the feeling for the transactions and state machine here? I am sure we could turn this into a card game...

**Comment by bhaugen** [comment]
The big state changes in that diagram are Committed, Fulfilled, and Fail.

Committed ends the Negotiation phase. Fulfilled ends the whole conversation happily. Fail ends the whole conversation unhappily.

**Comment by fosterlynn** [comment]
See also https://github.com/valueflows/valueflows/pull/503#issuecomment-502817140 and https://github.com/valueflows/valueflows/pull/503#issuecomment-502818333 from @bshambaugh.

**Comment by bhaugen** [comment]
@bshambaugh the diagram you posted is very similar to what we are working on here. Does the web of needs have a protocol (message sequence pattern, state machine, etc) something like CfA?
Some of the web of needs people were connected to UNCEFACT, which was connected to ebXML, which wrote up a version of CfA in this document: http://www.ebxml.org/specs/bpPATT_print.pdf

**Comment by fosterlynn** [comment]
I started thinking more about how to fit the conversations for action into the VF core, mostly to make sure it didn't affect the discussion of Proposal and Intent.  I think it can sit on top of the VF core, so am quitting working on this until someone needs it.  But I thought I'd record where I got to and also feedback from @bhaugen .

I worked with this diagram https://github.com/valueflows/forum.valueflo.ws/issues/133#issue-452005341, didn't compare to the others linked throughout this issue.

I think since the Proposal - Intent - Agreement - Commitment - Event model has its own internal ability to see where everything came from, through Fulfillment and Satisfaction, we can have multiple conversations fitting into that.  Specifically, I see negotiation conversations based on Proposal and ending in Agreement (or not), and probably multiple evaluation conversations later on based on Commitments of that Agreement.  When all Commitments have been agreed as fulfilled, then the Agreement is fulfilled, and the whole state machine above is done, on the happy path.

Might look something like this:
![cfa](https://user-images.githubusercontent.com/3776081/61144704-42da4e00-a49b-11e9-967b-9c15a748e0ec.png)

Bob also pointed out that there are 3 levels of transaction involved:
* each speech act must be signed and counter-signed by each party, so that each state is agreed upon
* each back and forth to some agreement gives a result, such as propose - accept, counter - accept, etc.
* the whole set in the above picture, including negotiation and evaluations, is tied together as one sort f mega-conversation.

Leaving it there for now....

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/133.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
