### ISSUE TITLE
Sensorica examples to explore REA and traditional accounting

### ISSUE THREAD

**Issue by bhaugen** [valueflows/forum.valueflo.ws#73]
@TiberiusB @serapath here's one starting point that I copied from a Sensorica document:
https://github.com/valueflows/valueflows/blob/master/use-cases/sensorica-custodian.md

Tibi, maybe you could fill in with more of Sensorica's details and concerns?

**Comment by serapath** [comment]
Hm, from a first glance, the `REA accounting` looks interesting. I'll skip more in-depth reading for now.
Thx. for all the corrections. Regarding people's bank (i just made up they all have an account at royal bank of canada), i did that, because i wanted to really account for every change that happens based on activity in that business scenario from a macro economic perspective. A payment includes changes to the balance sheet of the buyers and sellers bank accounts.

I'm still a bit confused about a few bits and pieces :-) ...
**Some more clarifying questions**
- How do "members" get paid by Sensorica and/or CAKE? Is it dividends or is it salary or do they invoice Sensorica and/or CAKE? (in the latter case they would need some form of self employment status and a tax number, right?)
- Entrepreneurs and investors usually face the risk of loss in case their predictions do not come true, but in the context of "Sensorica", "members" (**employees?**) seem to be able to invest their time and even lending/investing money in some form (in)to "Sensorica". If there will be revenue directly or indirectly connected to that investment, they get paid back, but if not, **will they face a loss?**
- Can `Jim` just print a part and temporary use it for his own benefit or for a fun experiment using up `Daniels` investment - "depriving" him from the chance that revenue will come from it?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/forum-valueflo-ws/-/issues/73.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
